module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#87d1e9",
        "secondary": "#05677d",
        "surface-container-highest": "#d5e3fc",
        "primary": "#004477",
        "surface-container-high": "#dce9ff",
        "outline-variant": "#c1c7d2",
        "on-primary-container": "#b4d4ff",
        "inverse-on-surface": "#eaf1ff",
        "on-background": "#0d1c2e",
        "on-tertiary-container": "#ffc59f",
        "inverse-primary": "#a0c9ff",
        "on-surface-variant": "#414750",
        "surface-variant": "#d5e3fc",
        "error-container": "#ffdad6",
        "secondary-fixed": "#b3ebff",
        "on-tertiary-fixed-variant": "#713700",
        "on-secondary-container": "#07687d",
        "on-secondary-fixed-variant": "#004e5f",
        "on-primary-fixed-variant": "#00497e",
        "on-error-container": "#93000a",
        "secondary-container": "#9be5fe",
        "tertiary": "#6b3300",
        "on-secondary-fixed": "#001f27",
        "surface": "#f8f9ff",
        "primary-fixed": "#d2e4ff",
        "on-primary-fixed": "#001c37",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#ffffff",
        "surface-container": "#e6eeff",
        "tertiary-container": "#8e4600",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0d1c2e",
        "on-tertiary-fixed": "#301400",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#233144",
        "background": "#f8f9ff",
        "surface-tint": "#1261a2",
        "tertiary-fixed-dim": "#ffb785",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#ccdbf3",
        "primary-fixed-dim": "#a0c9ff",
        "on-primary": "#ffffff",
        "outline": "#717781",
        "primary-container": "#055c9d",
        "error": "#ba1a1a"
      },
              "fontFamily": {
                      "display-lg": ["Quicksand"],
                      "label-sm": ["Nunito"],
                      "headline-lg-mobile": ["Quicksand"],
                      "body-lg": ["Nunito"],
                      "headline-md": ["Quicksand"],
                      "body-md": ["Nunito"],
                      "label-md": ["Nunito"],
                      "headline-lg": ["Quicksand"],
                      "sans": ["Nunito", "sans-serif"]
              },
    },
  },
  plugins: [],
}
